CREATE TABLE IF NOT EXISTS BOOK
(
    BOO_ID IDENTITY PRIMARY KEY,
    BOOK_NAME VARCHAR(255) NOT NULL UNIQUE
);
COMMENT
ON TABLE BOOK IS 'Таблица книг';
COMMENT
ON COLUMN BOOK.BOO_ID IS 'Идентификатор книги';
COMMENT
ON COLUMN BOOK.BOOK_NAME IS 'Название книги';

CREATE SEQUENCE BOOK_SEQ
    MINVALUE 1
    MAXVALUE 999999999
    INCREMENT BY 1
    START WITH 1
    NOCYCLE;