CREATE TABLE IF NOT EXISTS GENRE
(
    GEN_ID IDENTITY PRIMARY KEY,
    GENRE_NAME VARCHAR(255) NOT NULL UNIQUE
);
COMMENT
ON TABLE GENRE IS 'Таблица жанров';
COMMENT
ON COLUMN GENRE.GEN_ID IS 'Идентификатор жанра';
COMMENT
ON COLUMN GENRE.GENRE_NAME IS 'Название жанра';

CREATE SEQUENCE GENRE_SEQ
    MINVALUE 1
    MAXVALUE 999999999
    INCREMENT BY 1
    START WITH 1
    NOCYCLE;