CREATE TABLE IF NOT EXISTS BOOK_TO_AUTHOR
(
    BOO_ID BIGINT,
    AUT_ID BIGINT,
    CONSTRAINT BOO_AUT_ID
        PRIMARY KEY (BOO_ID, AUT_ID),
    CONSTRAINT BTA_BOO_ID_FK
        FOREIGN KEY (BOO_ID) REFERENCES BOOK ON DELETE CASCADE,
    CONSTRAINT ATB_AUT_ID_FK
        FOREIGN KEY (AUT_ID) REFERENCES AUTHOR ON DELETE CASCADE
);