CREATE TABLE IF NOT EXISTS BOOK_TO_GENRE
(
    BOO_ID BIGINT,
    GEN_ID BIGINT,
    CONSTRAINT GEN_BOO_ID
        PRIMARY KEY (BOO_ID, GEN_ID),
    CONSTRAINT BTG_BOO_ID_FK
        FOREIGN KEY (BOO_ID) REFERENCES BOOK ON DELETE CASCADE,
    CONSTRAINT BTG_GEN_ID_FK
        FOREIGN KEY (GEN_ID) REFERENCES GENRE ON DELETE CASCADE
);