CREATE TABLE IF NOT EXISTS AUTHOR
(
    AUT_ID IDENTITY PRIMARY KEY,
    AUTHOR_FIO VARCHAR(255) NOT NULL UNIQUE
);
COMMENT
    ON TABLE AUTHOR IS 'Таблица авторов';
COMMENT
    ON COLUMN AUTHOR.AUT_ID IS 'Идентификатор';
COMMENT
    ON COLUMN AUTHOR.AUTHOR_FIO IS 'ФИО автора';

CREATE SEQUENCE AUTHOR_SEQ
    MINVALUE 1
    MAXVALUE 999999999
    INCREMENT BY 1
    START WITH 10
    NOCYCLE;

CREATE TABLE IF NOT EXISTS BOOK
(
    BOO_ID IDENTITY PRIMARY KEY,
    BOOK_NAME VARCHAR(255) NOT NULL UNIQUE
);
COMMENT
    ON TABLE BOOK IS 'Таблица книг';
COMMENT
    ON COLUMN BOOK.BOO_ID IS 'Идентификатор книги';
COMMENT
    ON COLUMN BOOK.BOOK_NAME IS 'Название книги';

CREATE SEQUENCE BOOK_SEQ
    MINVALUE 1
    MAXVALUE 999999999
    INCREMENT BY 1
    START WITH 10
    NOCYCLE;

CREATE TABLE IF NOT EXISTS GENRE
(
    GEN_ID IDENTITY PRIMARY KEY,
    GENRE_NAME VARCHAR(255) NOT NULL UNIQUE
);
COMMENT
    ON TABLE GENRE IS 'Таблица жанров';
COMMENT
    ON COLUMN GENRE.GEN_ID IS 'Идентификатор жанра';
COMMENT
    ON COLUMN GENRE.GENRE_NAME IS 'Название жанра';

CREATE SEQUENCE GENRE_SEQ
    MINVALUE 1
    MAXVALUE 999999999
    INCREMENT BY 1
    START WITH 10
    NOCYCLE;

CREATE TABLE IF NOT EXISTS COMMENT
(
    COM_ID IDENTITY PRIMARY KEY,
    COMMENT_TEXT VARCHAR(255) NOT NULL,
    BOO_ID BIGINT REFERENCES BOOK (BOO_ID) ON DELETE CASCADE
);
COMMENT
    ON TABLE COMMENT IS 'Таблица комментариев';
COMMENT
    ON COLUMN COMMENT.COM_ID IS 'Идентификатор комментария';
COMMENT
    ON COLUMN COMMENT.COMMENT_TEXT IS 'Текст комментария';

CREATE SEQUENCE COMMENT_SEQ
    MINVALUE 1
    MAXVALUE 999999999
    INCREMENT BY 1
    START WITH 10
    NOCYCLE;

CREATE TABLE IF NOT EXISTS BOOK_TO_AUTHOR
(
    BOO_ID BIGINT,
    AUT_ID BIGINT,
    CONSTRAINT BOO_AUT_ID
        PRIMARY KEY (BOO_ID, AUT_ID),
    CONSTRAINT BTA_BOO_ID_FK
        FOREIGN KEY (BOO_ID) REFERENCES BOOK ON DELETE CASCADE,
    CONSTRAINT ATB_AUT_ID_FK
        FOREIGN KEY (AUT_ID) REFERENCES AUTHOR ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS BOOK_TO_GENRE
(
    BOO_ID BIGINT,
    GEN_ID BIGINT,
    CONSTRAINT GEN_BOO_ID
        PRIMARY KEY (BOO_ID, GEN_ID),
    CONSTRAINT BTG_BOO_ID_FK
        FOREIGN KEY (BOO_ID) REFERENCES BOOK ON DELETE CASCADE,
    CONSTRAINT BTG_GEN_ID_FK
        FOREIGN KEY (GEN_ID) REFERENCES GENRE ON DELETE CASCADE
);